name: mvml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.3.1
  - pip:
      - numpy==1.21.6
      - pandas==1.3.5
      - scikit-learn==1.0.2
      - feature-engine==1.4.0
      - joblib==1.2.0
      - gradio==3.19.1
